security:
  oauth2:
    client:
      clientId: 1002549059589-v22h4oe9vgvvijo6pch5e122s4p6rc03.apps.googleusercontent.com
      clientSecret: Dq0rmJE17JWDqKjhCN3dbevP
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false