pipeline {
  agent any
  environment {
    registry = "foxyfox/lvlup-spring"
    registryCredential = 'docker-technical-foxyfox'
    dockerImage = ''
    Staging_IP = '13.53.207.51'
    Production_IP = '13.53.65.221'
    DEV_DB_USERNAME = 'sa'
    DEV_DB_PASSWORD = ''
    DEV_DB_URL = 'jdbc:h2:mem:testdb'
    ACTIVE_PROFILE = 'test'
  }
  stages {
    stage('Build') {
      when {
        anyOf {
          branch 'master'
          branch 'Staging'
          branch 'Dev'
        }
      }
      steps {
        sh 'chmod +x ./gradlew'
        sh './gradlew bootJar'
      }
    }
    stage('Test') {
      when {
        anyOf {
          branch 'master'
          branch 'Staging'
          branch 'Dev'
        }
      }
      steps {
        sh './gradlew test'
      }
    }
    stage('Build and push docker image / Staging') {
      when {
        anyOf {
          branch 'Staging'
        }
      }
      steps {
        sh 'cp build/libs/lvlup-0.0.1-SNAPSHOT.jar ci/app.jar'
        script {
          dockerImage = docker.build(registry + ":staging", "./ci")
        }
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Build and push docker image / Production') {
      when {
        anyOf {
          branch 'master'
        }
      }
      steps {
        sh 'cp build/libs/lvlup-0.0.1-SNAPSHOT.jar ci/app.jar'
        script {
          dockerImage = docker.build( registry + ":$BUILD_NUMBER", "./ci")
        }
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            dockerImage.push('latest')
          }
        }
      }
    }
    stage('Deploy Staging') {
      when {
        anyOf {
          branch 'Staging'
          branch 'jenskins'
        }
      }
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: 'devops-lvlup-spring', keyFileVariable: 'KEY_FILE', passphraseVariable: '', usernameVariable: '')]) {
            sh "sh ci/deploy.sh $KEY_FILE ec2-user@$Staging_IP"
        }
      }
    }
    stage('Deploy Production') {
      when {
        branch 'master'
      }
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: 'devops-lvlup-spring', keyFileVariable: 'KEY_FILE', passphraseVariable: '', usernameVariable: '')]) {
            sh "echo Starting Deploy Script"
            sh "ssh -tt -i $KEY_FILE ec2-user@$Production_IP 'bash -s' < deploy.sh"
        }
      }
    }
  }
  post {
      failure {
        slackSend (
          channel: '#rueppellii-jenkins',
          color: 'danger',
          message: "${currentBuild.fullDisplayName} has died miserably. (<${env.BUILD_URL}|Open>)"
        )
      }
    }
}
